"""added cascade delete in aircraft for airline

Revision ID: 0001
Revises: 64050dc33b1d
Create Date: 2026-10-02 17:34:41.864891

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = "64050dc33b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("aircraft_airline_id_fkey", "aircraft", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_aircraft_airline_id_airline"),
        "aircraft",
        "airline",
        ["airline_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_aircraft_airline_id_airline"), "aircraft", type_="foreignkey"
    )
    op.create_foreign_key(
        "aircraft_airline_id_fkey", "aircraft", "airline", ["airline_id"], ["id"]
    )
    # ### end Alembic commands ###
