"""add unique constraints for seat and booking_seat

Revision ID: 1ea72b94f360
Revises: c0a966858e52
Create Date: 2026-09-22 14:06:29.344285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea72b94f360'
down_revision: Union[str, Sequence[str], None] = 'c0a966858e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_booking_seat', 'booking_seats', ['booking_id', 'seat_id'])
    op.create_unique_constraint('uq_seat_flight_number', 'seats', ['flight_id', 'seat_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_seat_flight_number', 'seats', type_='unique')
    op.drop_constraint('uq_booking_seat', 'booking_seats', type_='unique')
    # ### end Alembic commands ###
