"""remove unique constraint from airline name

Revision ID: 64050dc33b1d
Revises: d2466ec418ff
Create Date: 2026-09-29 14:26:25.312653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64050dc33b1d'
down_revision: Union[str, Sequence[str], None] = 'd2466ec418ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_airline_name', 'airline', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_airline_name', 'airline', ['name'])
    # ### end Alembic commands ###
