"""add tail_number and flight_number

Revision ID: d2466ec418ff
Revises: 1ea72b94f360
Create Date: 2026-09-22 14:48:23.348518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2466ec418ff'
down_revision: Union[str, Sequence[str], None] = '1ea72b94f360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft', sa.Column('tail_number', sa.String(length=20), nullable=False))
    op.create_unique_constraint(op.f('uq_aircraft_tail_number'), 'aircraft', ['tail_number'])
    op.drop_constraint(op.f('airline_iata_code_key'), 'airline', type_='unique')
    op.drop_constraint(op.f('airline_name_key'), 'airline', type_='unique')
    op.create_unique_constraint(op.f('uq_airline_iata_code'), 'airline', ['iata_code'])
    op.create_unique_constraint(op.f('uq_airline_name'), 'airline', ['name'])
    op.drop_constraint(op.f('airports_code_key'), 'airports', type_='unique')
    op.create_unique_constraint(op.f('uq_airports_code'), 'airports', ['code'])
    op.add_column('flights', sa.Column('departure_time', sa.DateTime(), nullable=False))
    op.add_column('flights', sa.Column('flight_number', sa.String(length=10), nullable=False))
    op.create_unique_constraint(op.f('uq_flights_flight_number'), 'flights', ['flight_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_flights_flight_number'), 'flights', type_='unique')
    op.drop_column('flights', 'flight_number')
    op.drop_column('flights', 'departure_time')
    op.drop_constraint(op.f('uq_airports_code'), 'airports', type_='unique')
    op.create_unique_constraint(op.f('airports_code_key'), 'airports', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_airline_name'), 'airline', type_='unique')
    op.drop_constraint(op.f('uq_airline_iata_code'), 'airline', type_='unique')
    op.create_unique_constraint(op.f('airline_name_key'), 'airline', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('airline_iata_code_key'), 'airline', ['iata_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_aircraft_tail_number'), 'aircraft', type_='unique')
    op.drop_column('aircraft', 'tail_number')
    # ### end Alembic commands ###
