app:
  name: "Airline Ticket Sales"
  host: "0.0.0.0"
  port: 8000
  secret_key: "raif2008"
  debug: true

database:
  user: 'user'
  password: 'password'
  host: 'localhost'
  port: 5433
  name: 'flightdb'


access_token:
  lifetime_seconds: 3600
  reset_password_token_secret: "reset-secret-phrase"
  verification_token_secret: "verify-secret-phrase"

